# configs/cifar10.yaml
dataset: cifar10
model_save_path: best_model.pkl
random_seed: 42

# Batch size configuration
batch_size: 32
effective_batch_size: 512

# Training parameters
learning_rate: 0.001
num_epochs: 120
noise_std: 1.0
delta: 1e-5
max_epsilon: 10.0

# Data augmentation configuration
use_augmentation: true
augment_mult: 4

# EMA configuration
use_ema: true
ema:
  mu: 0.999
  use_warmup: true
  start_step: 0
  eval_with_ema: true

# Custom augmentation parameters for CIFAR-10
augmentation:
  random_crop: true
  crop_size: [32, 32]
  crop_padding: 4
  random_flip: true
  flip_prob: 0.5
  random_brightness: true
  brightness_delta: 0.2
  random_contrast: true
  contrast_range: [0.8, 1.2]
  random_saturation: true
  saturation_range: [0.8, 1.2]
  random_hue: true
  hue_delta: 0.1
