dataset: fashion_mnist
model_save_path: best_model.pkl
random_seed: 42

# Batch size configuration
batch_size: 64
effective_batch_size: 256

# Training parameters
learning_rate: 0.001
num_epochs: 100
noise_std: 1.0
delta: 1e-5
max_epsilon: 10.0

# Data augmentation configuration
use_augmentation: false

# EMA configuration
use_ema: false
